package com.sohlman.liferay.foobar.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Bar service. Represents a row in the &quot;perpoc_Bar&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sohlman.liferay.foobar.model.impl.BarModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sohlman.liferay.foobar.model.impl.BarImpl}.
 * </p>
 *
 * @author Sampsa Sohlman
 * @see Bar
 * @see com.sohlman.liferay.foobar.model.impl.BarImpl
 * @see com.sohlman.liferay.foobar.model.impl.BarModelImpl
 * @generated
 */
public interface BarModel extends BaseModel<Bar>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a bar model instance should use the {@link Bar} interface instead.
     */

    /**
     * Returns the primary key of this bar.
     *
     * @return the primary key of this bar
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this bar.
     *
     * @param primaryKey the primary key of this bar
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the bar ID of this bar.
     *
     * @return the bar ID of this bar
     */
    public long getBarId();

    /**
     * Sets the bar ID of this bar.
     *
     * @param barId the bar ID of this bar
     */
    public void setBarId(long barId);

    /**
     * Returns the group ID of this bar.
     *
     * @return the group ID of this bar
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this bar.
     *
     * @param groupId the group ID of this bar
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this bar.
     *
     * @return the company ID of this bar
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this bar.
     *
     * @param companyId the company ID of this bar
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this bar.
     *
     * @return the user ID of this bar
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this bar.
     *
     * @param userId the user ID of this bar
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this bar.
     *
     * @return the user uuid of this bar
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this bar.
     *
     * @param userUuid the user uuid of this bar
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this bar.
     *
     * @return the user name of this bar
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this bar.
     *
     * @param userName the user name of this bar
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this bar.
     *
     * @return the create date of this bar
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this bar.
     *
     * @param createDate the create date of this bar
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this bar.
     *
     * @return the modified date of this bar
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this bar.
     *
     * @param modifiedDate the modified date of this bar
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the value of this bar.
     *
     * @return the value of this bar
     */
    @AutoEscape
    public String getValue();

    /**
     * Sets the value of this bar.
     *
     * @param value the value of this bar
     */
    public void setValue(String value);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Bar bar);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Bar> toCacheModel();

    @Override
    public Bar toEscapedModel();

    @Override
    public Bar toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
